### ISSUE TITLE
Triggering rebuild - failure due to system outage

### ISSUE THREAD

**Issue by jonathon-love** [flathub/org.jamovi.jamovi#23]
hi, i don't suppose there's a way *i* can trigger a rebuild for this:

https://flathub.org/builds/#/builders/2/builds/3494

with thanks

**Comment by nedrichards** [comment]
hrm, if you login with your github account (press the link in the top right that says 'Anonymous') and press the rebuild button, does it work? I'll give it a go as well.

**Comment by jonathon-love** [comment]
if i do that, it says `Cannot rebuild: you need to have role 'flathub'`

**Comment by nedrichards** [comment]
Sorry, that's frustrating. The only way of you triggering an autorebuild on your own then is pushing an empty commit, which is gross and lame. Apologies.
