### ISSUE TITLE
issues on arm hardware

### ISSUE THREAD

**Issue by jonathon-love** [flathub/org.jamovi.jamovi#26]
hi,

i don't have access to arm hardware to try this myself, but a user is reporting the following:

```
(xenial)oli@localhost:~$ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
(xenial)oli@localhost:~$ flatpak install flathub org.jamovi.jamovi
Skipping: org.jamovi.jamovi/aarch64/stable is already installed
(xenial)oli@localhost:~$ flatpak install flathub org.jamovi.jamovi
Skipping: org.jamovi.jamovi/aarch64/stable is already installed
(xenial)oli@localhost:~$ flatpak run org.jamovi.jamovi
error: app/org.jamovi.jamovi/aarch64/master not installed
```

is there something obvious we're overlooking?

with thanks

**Comment by TingPing** [comment]
`flatpak run org.jamovi.jamovi/aarch64/stable` should work. If they have the latest flatpak version that is a bug to report there.

**Comment by olioliv1** [comment]
Hello,

i tried to remove jamovi and to re-install it the same way i did before with : flathub.flatpakrepo from flathub and i go there : 
--------------------------------------------------
(xenial)oli@localhost:~$ 
(xenial)oli@localhost:~$ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
(xenial)oli@localhost:~$ flatpak install flathub org.jamovi.jamovi
Required runtime for org.jamovi.jamovi/aarch64/stable (runtime/org.freedesktop.Platform/aarch64/1.6) found in remote flathub
Do you want to install it? [y/n]: y
Installing in system:
org.freedesktop.Platform/aarch64/1.6        flathub 8180958bb3af
org.freedesktop.Platform.ffmpeg/aarch64/1.6 flathub 09b31555a32d
org.freedesktop.Platform.Locale/aarch64/1.6 flathub 6abc7bbbb064
org.jamovi.jamovi/aarch64/stable            flathub e4a89a88844f
  permissions: ipc, network, pulseaudio, wayland, x11, dri
  file access: home
org.jamovi.jamovi.Locale/aarch64/stable     flathub e52c5f1a2292
Is this ok [y/n]: 
Is this ok [y/n]: y
Installing: org.freedesktop.Platform/aarch64/1.6 from flathub
[####################] 1 metadata, 5892 content objects fetched; 76202 KiB trans
error: Failed to install org.freedesktop.Platform/aarch64/1.6: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Flatpak system operation Deploy not allowed for user
(xenial)oli@localhost:~$ 
-------------------------------------------------------------------

Oli

**Comment by jonathon-love** [comment]
what version of flatpak do you have installed oli?

with thanks

**Comment by olioliv1** [comment]
this one 
flatpak is already the newest version (1.0.0-flatpak2~xenial).

**Comment by jonathon-love** [comment]
@TingPing,

any tips on this?

with thanks

**Comment by nedrichards** [comment]
No real idea - the only thing I'd point out is that this is an actual flatpak bug and should be filed in https://github.com/flatpak/flatpak (and then probably closed here)

**Comment by jonathon-love** [comment]
hi @olioliv1 

could you report this issue over at https://github.com/flatpak/flatpak/issues

i'd submit it for you, but it want me to provide details about your system.

with thanks
