### ISSUE TITLE
app.makeSingleInstance() does not work

### ISSUE THREAD

**Issue by jonathon-love** [flathub/org.jamovi.jamovi#27]
hi,

electron applications make use of [`app.makeSingleInstance()`](https://electronjs.org/docs/api/app#appmakesingleinstancecallback) to ensure that only one copy of an application is running -- but this doesn't seem to work with the flatpak.

i assume this is due to the sandboxing interfering with the communications between the new instance, and the existing instance of the application, but i'm not sure how to enable this.

do you guys have any experience with `makeSingleInstance()` and flatpaks? (i can't find any documentation on how makeSingleInstance works)

with thanks

**Comment by nedrichards** [comment]
@matthiasclasen this feels somewhat related to some of the things you've been musing about GApplication, otherwise @alexlarsson is the expert on all things low level and flatpak.

**Comment by matthiasclasen** [comment]
For Linux desktop apps, the canonical way to ensure uniqueness is to claim a bus name on the session bus. I don't know what electron does.

**Comment by jonathon-love** [comment]
ok, digging deeper, file locks does seem to be the way that electron/chromium achieves this.

chromium/electron first creates a 'userData' path, then creates files in there with names like `SingletonLock`.

running the app normally creates these files in `~/.config/app_name`, running inside the flatpak, querying the 'userData' from inside the application yields: `~/.var/app/org.app.App/config/app_name`.

but if i look in this directory, there's no `SingletonLock` or those appropriate files.

is there something in the flatpak which would prevent the creation of these files?

in other news [here's](https://forum.snapcraft.io/t/electron-snap-killed-when-using-app-makesingleinstance-api/2667/21) a long thread discussing similar issues in snaps. possibly related?

with thanks

**Comment by jonathon-love** [comment]
ah, i see. if i 'enter the flatpak' (`flatpak run --devel --command=bash org.jamovi.jamovi`), then run the application, then navigate to `~/.var/app/org.jamovi.jamovi/config/jamovi`, i find all the `SingletonLock` files etc. to be in place. however, while the flatpak is running, i look at that fs location from outside the flatpak, i see that those files aren't there.

what would be the recommended strategy to make these files visible across running flatpak instances?

with thanks

**Comment by matthiasclasen** [comment]
that should just work. It certainly works here, in my test. Does jamovi actually use $XDG_CONFIG_HOME or does it hardcode $HOME/.config ?

**Comment by jonathon-love** [comment]
hi, electron uses the `$XDG_CONFIG_HOME`; if i override it, the location of the `SingletonLock` files change accordingly.

interestingly, if i force electron to use ~/.config (i.e. a location outside the flatpak), the `SingletonLock` files are created as expected, but if i run a second instance, the second instance completely ignores (presumably doesn't *see*) the `SingletonLock` files, and replaces them with its own (this isn't an issue when you run outside the flatpak).

electron uses broken symlinks for the `SingletonLock` ... there's not a sandbox policy that would interfere with 'seeing' them?

with thanks

**Comment by matthiasclasen** [comment]
Broken symlinks, hmm. I don't know. Broken how ? where do they point ?
Creating a bar -> foo link to a nonexisting file shows up inside and outside the sandbox here.

**Comment by jonathon-love** [comment]
ah, so i wonder if it could be the last one which is the issue

```
lrwxrwxrwx  1 jonathon jonathon    20 Sep  8 09:30 SingletonCookie -> 15082564980386267495
lrwxrwxrwx  1 jonathon jonathon    24 Sep  8 09:30 SingletonLock -> jonathon-VirtualBox-2249
lrwxrwxrwx  1 jonathon jonathon    37 Sep  8 09:30 SS -> /tmp/.org.chromium.Chromium.9ttAio/SS
```

**Comment by jonathon-love** [comment]
ah! that's it!

if i run it with `flatpak run --filesystem=/tmp org.jamovi.jamovi` it works.

although, now i suppose i've got to figure out a strategy that doesn't require giving access to all of /tmp. the path changes each time :/

**Comment by matthiasclasen** [comment]
the symlink to /tmp is indeed what is breaking this - each sandbox gets its own /tmp, so that is not the right way to share things between instances. If it put the file right into $XDG_CONFIG_HOME, things would just work, I think

**Comment by jonathon-love** [comment]
yup. the issue is that this is electron, so where it puts things may be outside my control. but i'll keep looking into it.
