### ISSUE TITLE
Missing icon on flathub pages

### ISSUE THREAD

**Issue by jonathon-love** [flathub/org.jamovi.jamovi#3]
hey,

i notice that other apps have an icon to the top right of their page, i.e.

https://beta.flathub.org/apps/details/net.ankiweb.Anki

but i'm wondering why our icon isn't showing up in this location?

with thanks

**Comment by nedrichards** [comment]
Yes, it's because there's an issue in appstream generation somewhere. I just noticed that the category and icon wasn't being correctly populated in there earlier today.

**Comment by jonathon-love** [comment]
so is this something i'm responsible for?

**Comment by TingPing** [comment]
No it is an issue on our end and should be fixed very soon.

**Comment by jonathon-love** [comment]
this *looks* like it's fixed, the icon now appears, but i notice the page here:

https://flathub.org/apps/details/org.jamovi.jamovi

 is not yet in sync with

https://github.com/flathub/org.jamovi.jamovi/blob/master/org.jamovi.jamovi.appdata.xml

(i updated the release notes)

but that's because the flathub.org only updates itself periodically from the flathub repo?

with thanks

**Comment by jonathon-love** [comment]
that does appear to be the case.
