### ISSUE TITLE
Update runtime to 19.08

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.jamovi.jamovi#30]

**Comment by jonathon-love** [comment]
hi, i assume you mean 18.08, but the corresponding `org.freedesktop.Sdk.Extension.gfortan-62//18.08` doesn't seem to be available yet.

**Comment by nedrichards** [comment]
I believe gfortran is actually shipped in the 18.08 runtime rather than as an extension (it'll probably go back outside in the 19. versions but is in there for now)

**Comment by jonathon-love** [comment]
hi @nedrichards,

is there a trick to using it? this used to work:

```
Starting build of org.jamovi.jamovi
========================================================================
Building module gfortran in /home/jonathon/Documents/org.jamovi.jamovi/.flatpak-builder/build/gfortran-1
========================================================================
Running: /usr/lib/sdk/gfortran-62/install.sh
/bin/sh: /usr/lib/sdk/gfortran-62/install.sh: No such file or directory
Error: module gfortran: Child process exited with code 127
```

with thanks

**Comment by TingPing** [comment]
Just remove that command entirely.

**Comment by jonathon-love** [comment]
righto. and what's the new path to the compiler? it used to be:

`/usr/lib/sdk/gfortran-62/bin/gfortran`

(point me in the right direction if there's documentation on this i'm not finding)

with thanks

**Comment by jonathon-love** [comment]
hi,

i'm trying to update my flatpak to the 19.08 runtime, however the compilation of one of my project's components is unexpectedly exiting with code 1, without any error message.

i'm wondering if i'm hitting a resource limit, or similar?

with thanks

**Comment by jonathon-love** [comment]
done.
