### ISSUE TITLE
can't install 

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.jamovi.jamovi#33]
flatpak install flathub org.jamovi.jamovi
Installing in system:
org.jamovi.jamovi/x86_64/stable flathub 6fd0d4e868bb
  permissions: ipc, network, pulseaudio, x11, dri
  file access: home
  dbus access: org.freedesktop.Notifications
Is this ok [y/n]: y
Instalando: org.jamovi.jamovi/x86_64/stable desde flathub
[####################] 1 metadata, 0 content objects fetched; 569 B transferred 
error: Failed to instalar org.jamovi.jamovi/x86_64/stable: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error pulling from repo: While pulling app/org.jamovi.jamovi/x86_64/stable from remote flathub: Opening content object 0b20e9ca497d219ee235dd7faca237f2051a8d7b1f4421dff88c2abc595e1a4a: Opening content object 0b20e9ca497d219ee235dd7faca237f2051a8d7b1f4421dff88c2abc595e1a4a: Couldn't find file object '0b20e9ca497d219ee235dd7faca237f2051a8d7b1f4421dff88c2abc595e1a4a'

**Comment by Lvaskz** [comment]
Linuxmint 19
cinnamon 
64 bits

**Comment by jonathon-love** [comment]
hi luis,

i just tried this here on mint 19, and it worked without issue. could you try a second time? it was perhaps a temporary outage with flathub.

with thanks

**Comment by Lvaskz** [comment]
OK I will

**Comment by Lvaskz** [comment]
OK I installed
