### ISSUE TITLE
Icon missing

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.jamovi.jamovi#34]
Hi I installed it in Linux mint 19.
The icon in the Taskbar is missing. The image is the 9.5.9 version but with the latest is the same issue.

**Comment by Lvaskz** [comment]
![captura de pantalla de 2018-11-25 10-24-19](https://user-images.githubusercontent.com/29207169/49343664-5daa3180-f633-11e8-955b-fd8b4aca39e8.png)

**Comment by jonathon-love** [comment]
hi,

thanks for reporting.

flathub folks, i've double-checked and i can't see what i'm doing wrong. there *is* an app icon in the launcher menu, but not in the task bar.

https://github.com/flathub/org.jamovi.jamovi/blob/master/org.jamovi.jamovi.json#L538

any idea what i could be doing wrong?

with thanks

**Comment by TingPing** [comment]
@jonathon-love 	Well you are relying on `"rename-icon"` here so you are just referencing the old name somewhere probably. I'd suggest using the same name always to avoid such issues.

**Comment by Lvaskz** [comment]
Hi, any progress?

**Comment by jonathon-love** [comment]
hi, sorry,

it looks to me to be a bug in freedesktop, or the window manager. there's only one place where the path to an icon is specified, and that's specified correctly (otherwise the desktop icon wouldn't appear).

i've looked at other apps which *do* have their icons in the menu, and they're doing *exactly* what i'm doing.

so i'm a bit stumped.

**Comment by TingPing** [comment]
> it looks to me to be a bug in freedesktop, or the window manager. there's only one place where the path to an icon is specified, and that's specified correctly (otherwise the desktop icon wouldn't appear).

To be clear you are talking about where its referenced in your codebase right?

**Comment by Lvaskz** [comment]
any progress?

**Comment by jonathon-love** [comment]
> To be clear you are talking about where its referenced in your codebase right?

ah, good insight @TingPing, i had been assuming that the app icon was provided by all that meta-y stuff, and didn't realise i need to have a call to a *set icon function* inside my application.

thanks for chasing this up @Lvaskz, this should be fixed in the next release.

cheers

**Comment by Lvaskz** [comment]
Great!!

**Comment by Lvaskz** [comment]
icon still missing with 0.9.5.17

**Comment by jonathon-love** [comment]
just pushed an update, try that.

**Comment by Lvaskz** [comment]
Thanks now it shows properly.
