### ISSUE TITLE
font problems in flatpaks

### ISSUE THREAD

**Issue by jonathon-love** [flathub/org.jamovi.jamovi#41]
hi,

our flatpak works great, however we do get the occasional report of fonts not rendering correctly, i.e.:

https://github.com/jamovi/jamovi/issues/740

have you guys encountered these sorts of issues in the past? i'm wondering if it's locale related.

with thanks

jonathon

**Comment by TingPing** [comment]
Did you reproduce it yourself? Flatpak pulls in host fontconfig settings which could very well be broken on their system.

**Comment by jonathon-love** [comment]
hi,

no, i've been unable to reproduce it -- but it's helpful to know that font stuff comes from the host system.

i'll do a bit more digging.

with thanks

**Comment by jonathon-love** [comment]
> Flatpak pulls in host fontconfig settings which could very well be broken on their system.

so it doesn't look like their fontconfig settings are broken. if i get them to run the same plotting code outside of the flatpak, everything behaves correctly.

is there something else in can look into?

with thanks

**Comment by TingPing** [comment]
I'm sure thats the right area to look into, fontconfig provides some tools you can run inside and out to see what differs.

**Comment by jonathon-love** [comment]
hi,

so we've found that running the following fixes the issue:

```
flatpak run --command=fc-cache org.jamovi.jamovi -f -v
```

but i'm scratching my head to figure out how i can address this issue without the user having to run this command.

any suggestions?

with thanks

**Comment by TingPing** [comment]
You should probably open an issue against flatpak/flatpak saying the font cache isn't being updated properly or such.

If it solves your problem in the short term and you can accept the slower startup perhaps just run this in the package as a workaround.

**Comment by jonathon-love** [comment]
this is still an outstanding issue, however, we've been able to find a different rendering pipeline which bypasses the issue.
