### ISSUE TITLE
update freedesktop runtime to 20.08

### ISSUE THREAD

**Issue by eszlari** [flathub/org.jamovi.jamovi#62]

**Comment by sjentsch** [comment]
Working on it with Jonathon.

**Comment by hfiguiere** [comment]
21.08 is available now.

**Comment by sjentsch** [comment]
It currently doesn't even compile with 20.08.
https://github.com/flatpak/flatpak-builder/issues/415

**Comment by hfiguiere** [comment]
it's just twice the work.

**Comment by jonathon-love** [comment]
> Unlikely that moving to 21.08 will make that any better.

haha, i have the opposite thought ... works with 19.08 and earlier, it works with 20.08 but after being built on flathub crashes, there's a very good chance that on 21.08 it will **just work** :)

**Comment by sjentsch** [comment]
Wishful thinking...
Nope, it doesn't compile:
Error: module gsl: Child process exited with code 137
I tried upgrading gsl to 2-7 but that did not solve it either.

**Comment by hfiguiere** [comment]
it's thin as an error message to be able to help.

**Comment by hfiguiere** [comment]
dupe of #74 that is still open to followup on runtime issues.
