### ISSUE TITLE
Jamovi pulling up blank on Chromeboom

### ISSUE THREAD

**Issue by corinnemargo** [flathub/org.jamovi.jamovi#64]
Hi there! I have followed all the steps and then when I go to open Jamovi ion my chromebook, only a white blank screen appears?

**Comment by jonathon-love** [comment]
hi, see here:

https://www.jamovi.org/user-manual.html#blank-screen-at-startup-on-chromebooks

cheers

jonathon

**Comment by corinnemargo** [comment]
Hi there!

I did that and it is still blank:

Enter chrome://flags/ into the ChromeOS address bar. This will bring up “Experiments”. Search for Crostini GPU Support and set...



Warmly,
Corinne

CORINNE WAINER
Ed.M., CPT, E-RYT, YACEP, KRI
♒︎ Co-Founder, CBO, + Director of Barre Education at SHAKTIBARRE
PhD Student via The New School
Marketing for S*M*B
Education at AFPA



✨ A.k.a The Yoga-Barre Empowerment Hub (VOGUE, 2016), SHAKTIBARRE offers effective, compassionate, and connected barre and yoga classes for everybody while innovating our fitness industry through metrics that empower and include.

**Comment by jonathon-love** [comment]
hi,

just confirming, you set it to **disabled**, and then you've restarted your chromebook?

with thanks

**Comment by corinnemargo** [comment]
Hi there!

Yes I did.



Warmly,
Corinne

CORINNE WAINER
Ed.M., CPT, E-RYT, YACEP, KRI
♒︎ Co-Founder, CBO, + Director of Barre Education at SHAKTIBARRE
PhD Student via The New School
Marketing for S*M*B
Education at AFPA



✨ A.k.a The Yoga-Barre Empowerment Hub (VOGUE, 2016), SHAKTIBARRE offers effective, compassionate, and connected barre and yoga classes for everybody while innovating our fitness industry through metrics that empower and include.

**Comment by jonathon-love** [comment]
what sort of device do you have?

with thanks

**Comment by corinnemargo** [comment]
Hi there!

I have a chromebook



Warmly,
Corinne

CORINNE WAINER
Ed.M., CPT, E-RYT, YACEP, KRI
♒︎ Co-Founder, CBO, + Director of Barre Education at SHAKTIBARRE
PhD Student via The New School
Marketing for S*M*B
Education at AFPA



✨ A.k.a The Yoga-Barre Empowerment Hub (VOGUE, 2016), SHAKTIBARRE offers effective, compassionate, and connected barre and yoga classes for everybody while innovating our fitness industry through metrics that empower and include.

**Comment by jonathon-love** [comment]
hey,

do you know what sort of chromebook you have? there's lots of different brands and models for example.

with thanks

**Comment by jonathon-love** [comment]
i suspect there's something unusual about your particular model of chromebook, and you'll probably need to use our cloud based version instead:

https://cloud.jamovi.org

kind regards

**Comment by corinnemargo** [comment]
I think it is this one
https://www.walmart.com/ip/SAMSUNG-Chromebook-4-11-6-Intel-Celeron-Processor-N4000-4GB-RAM-32GB-eMMC-Intel-UHD-Graphics-600-XE310XBA-K01US-Google-Classroom-Ready/558190726


Warmly,
Corinne

*CORINNE WAINER*
*Ed.M., CPT, E-RYT, YACEP, KRI*
♒︎ *Co-Founder, CBO, + Director of Barre Education at SHAKTIBARRE
<http://www.shaktibarre.com>*
*PhD
<https://www.newschool.edu/nssr/phd-cognitive-social-developmental-psychology/>
Student via The New School*
*Marketing for S*M*B <https://supermegaboss.com/>*
*Education at AFPA <https://www.afpafitness.com/>*



✨ *A.k.a The Yoga-Barre Empowerment Hub (VOGUE, 2016), SHAKTIBARRE offers
effective, compassionate, and connected barre and yoga classes for
everybody while innovating our fitness industry through metrics that
empower and include.*
