### ISSUE TITLE
Issues accessing the home directory

### ISSUE THREAD

**Issue by jonathon-love** [flathub/org.jamovi.jamovi#7]
hi,

our flatpak works nicely, however on one person's computer, the call to (python) `os.listdir()` in the users home directory fails with a permission denied.

this same user, if they download the `org.jamovi.jamovi` repo, build it, and run it, it works fine.

any tips on how we might figure out what's at play here?

with thanks

**Comment by TingPing** [comment]
> this same user, if they download the org.jamovi.jamovi repo, build it, and run it, it works fine.

How are they running it?

**Comment by jonathon-love** [comment]
```
flatpak-builder --run appdir org.jamovi.jamovi jamovi
```

**Comment by TingPing** [comment]
That bypasses the sandboxing permissions.

**Comment by jonathon-love** [comment]
ah ok. i'll have them install it and see if it works.

(however, there remains the riddle or why it works on other computers.)

with thanks

**Comment by TingPing** [comment]
Version of `flatpak` might be relevant. Since this grants complete access to home it just makes a bind mount of it.

**Comment by jonathon-love** [comment]
yeah, i figured as much, and did get them to update their flatpak from the alexlarson ppa, uninstall, reinstall jamovi. but i'll double-check those upgrades did work as expected.

**Comment by raviselker** [comment]
Hi,

I installed `org.jamovi.jamovi` from a locally built repo with:

```flatpak --user install local-repo org.jamovi.jamovi```

Using flatpak version 0.11.3. the application receives a ‘permission denied’ when accessing the home directory. This is the same behaviour as when installing from flathub. So far this behaviour is unique to my computer, and doesn’t occur on others.

**Comment by TingPing** [comment]
What exactly does "accessing the home directory" entail? Can you run `flatpak run --command=sh org.jamovi.jamovi` and list/cat/touch files in the home directory?

**Comment by jonathon-love** [comment]
ah, the issue was accessing the `~/Documents` directory, and that was a fat32 mount.

thanks for the handy debugging tip.
