### ISSUE TITLE
Crash after last update (Linux Mint)

### ISSUE THREAD

**Issue by sbadux** [flathub/org.jamovi.jamovi#73]
Hello,
when I try to start jamovi (jamovi org.jamovi.jamovi 2.0.2 stable system)
it crashes:

`
enrico@enrico-cubi:~$ flatpak run org.jamovi.jamovi
[5 zypak-helper] Portal v4 is not available
Gtk-Message: 16:08:55.652: Failed to load module "xapp-gtk3-module"
jamovi
version: 0.0.0
cli:     0.0.0

ports: 38767, 33221, 46667

jamovi.server.session - creating instance: cfc33bf2-70ab-4492-b14a-c5a74f4466bc
instance_started cfc33bf2-70ab-4492-b14a-c5a74f4466bc

terminate called without an active exception

terminate called without an active exception

terminate called without an active exception

terminate called without an active exception

jamovi.server.engine - Engine crash (spontaneous) with exit code -6

[13 zypak-sandbox] Dropping 0x1d85240 (3) because of connection closed
[13 zypak-sandbox] Host is gone, preparing to exit...
[13 zypak-sandbox] Quitting Zygote...
`

**Comment by jonathon-love** [comment]
We've pushed a fix, it will be available in about 6 hours (the time it takes the build machinery to complete)

**Comment by sbadux** [comment]
Thank you very much!
Now it's fixed and the program is loaded correctly.
