### ISSUE TITLE
Adding mimetype at install

### ISSUE THREAD

**Issue by jonathon-love** [flathub/org.jamovi.jamovi#9]
am i able to add a `/app/share/mime/application/org.jamovi.jamovi.xml` and register a new mimetype with my flatpak?

with thanks

**Comment by jonathon-love** [comment]
that's a 'yes'.

**Comment by nedrichards** [comment]
Yep! anything you export needs to have the app id filename pattern, but basically anything useful can get out there.

**Comment by TingPing** [comment]
Also a gotcha is that the icons referenced in the mimetype must also match your app-id.
